
2022-08-28 10:16:05,068 Downloading and reading train artifact
Traceback (most recent call last):
  File "run.py", line 176, in <module>
    go(args)
  File "run.py", line 31, in go
    df = pd.read_csv(train_data_path, low_memory=False)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file